name: Build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgl-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B bin -DCMAKE_BUILD_TYPE=Release .
          cmake --build bin --parallel 4
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenNFS-Linux
          path: |
            bin/OpenNFS
            resources
            shaders
            LICENSE
            README.md

  Release:
    needs: [Linux, Windows, MacOS]
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Zip artifacts
        run: |
          mkdir release_assets
          cd artifacts
          for dir in OpenNFS-*; do
            if [ -d "$dir" ]; then
              zip -r "../release_assets/$dir.zip" "$dir"
            fi
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*.zip
          prerelease: false
          name: OpenNFS ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B bin -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build bin --config Release --parallel 4
          cp LICENSE LICENSE.txt
          cp bin\Release\OpenNFS.exe bin\
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenNFS-Windows
          path: |
            bin/OpenNFS.exe
            resources
            shaders
            LICENSE.txt
            README.md

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B bin -DCMAKE_BUILD_TYPE=Release .
          cmake --build bin --config Release --parallel 3
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenNFS-MacOS
          path: |
            bin/OpenNFS
            resources
            shaders
            LICENSE
            README.md

